// PassageLab — app/terms/page.tsx
// NOTE: This is a starting-point terms of service. Have it reviewed by a
// lawyer before relying on it.

import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — PassageLab',
}

const SERIF = "'Playfair Display', Georgia, serif"
const SLATE = '#8892A4'

function H({ children }: { children: React.ReactNode }) {
  return <h2 style={{ fontFamily: SERIF, fontSize: 20, fontWeight: 700, margin: '32px 0 10px' }}>{children}</h2>
}

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px', lineHeight: 1.8, fontSize: 14 }}>
      <Link href="/" style={{ color: '#C9973A', textDecoration: 'none', fontSize: 13 }}>← Back to PassageLab</Link>
      <h1 style={{ fontFamily: SERIF, fontSize: 32, fontWeight: 700, margin: '20px 0 6px' }}>Terms of Service</h1>
      <p style={{ color: SLATE, fontSize: 13 }}>Last updated: June 2026</p>

      <H>1. The Service</H>
      <p>PassageLab generates AI-assisted biblical study material. The free Overview tab is available to everyone; additional study tabs are unlocked per passage at the prices shown ($1 Quick Study, $2 Deep Dive) and billed once at the end of each month to your saved card.</p>

      <H>2. Accounts &amp; Billing</H>
      <p>You must provide accurate account information and keep your credentials secure. A verified payment card is required to unlock paid studies. Unlocked studies are tallied during the month and charged in a single payment on or after the 1st of the following month. You may set a monthly spending limit in your account; studies that would exceed it are blocked. All sales are final once study content has been generated, but if something goes wrong we will make it right — contact us.</p>

      <H>3. AI-Generated Content</H>
      <p>Study content is generated by AI language models. It is a research aid, not a substitute for your own study, judgment, or the counsel of your community. Citations, dates, quotes, and archaeological details should be verified before use in academic or published work. We do not guarantee the accuracy, completeness, or theological alignment of generated content.</p>

      <H>4. Acceptable Use</H>
      <p>You agree not to abuse the service: no automated scraping or bulk generation, no attempts to bypass payment or rate limits, no reselling of generated content as a competing service, and no use that violates applicable law.</p>

      <H>5. Intellectual Property</H>
      <p>You may use generated study content freely in your sermons, lessons, papers, and ministry work. The PassageLab name, design, and software remain our property. Bible text is drawn from public domain translations (KJV, WEB, ASV, YLT).</p>

      <H>6. Affiliate Links</H>
      <p>Book recommendations may include affiliate links (Amazon, Logos, Christianbook). We may earn a commission on purchases at no extra cost to you.</p>

      <H>7. Disclaimers &amp; Liability</H>
      <p>The service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law, our total liability for any claim arising from the service is limited to the amount you paid us in the three months before the claim.</p>

      <H>8. Changes &amp; Termination</H>
      <p>We may update these terms or modify the service; material changes will be announced on this page. You may close your account at any time; outstanding usage will be billed in the next cycle. We may suspend accounts that violate these terms.</p>

      <H>9. Contact</H>
      <p>Questions about these terms: <a href="mailto:support@passagelab.app" style={{ color: '#C9973A' }}>support@passagelab.app</a></p>
    </div>
  )
}
