// PassageLab — app/terms/page.tsx
// NOTE: This is a starting-point terms of service. Have it reviewed by a
// lawyer before relying on it.

import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — PassageLab',
}

const SERIF = "'Playfair Display', Georgia, serif"
const SLATE = '#8892A4'

function H({ children }: { children: React.ReactNode }) {
  return <h2 style={{ fontFamily: SERIF, fontSize: 20, fontWeight: 700, margin: '32px 0 10px' }}>{children}</h2>
}

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px', lineHeight: 1.8, fontSize: 14 }}>
      <Link href="/" style={{ color: '#C9973A', textDecoration: 'none', fontSize: 13 }}>← Back to PassageLab</Link>
      <h1 style={{ fontFamily: SERIF, fontSize: 32, fontWeight: 700, margin: '20px 0 6px' }}>Terms of Service</h1>
      <p style={{ color: SLATE, fontSize: 13 }}>Last updated: June 2026</p>

      <H>1. The Service</H>
      <p>PassageLab generates AI-assisted biblical study material. The free Overview tab is available to everyone, and each account&apos;s first Quick Study is free. Additional study tabs are unlocked per passage at the prices shown ($2 Quick Study, $5 Deep Dive); a valid payment method is required, and your saved card is charged at the moment you unlock a study.</p>

      <H>2. Accounts &amp; Billing</H>
      <p>You must provide accurate account information and keep your credentials secure. A verified payment card is required to unlock paid studies. Each account&apos;s first Quick Study is free; after that, your card is charged at the moment you unlock a study. You may set a monthly spending limit in your account; studies that would exceed it are blocked. All sales are final once study content has been generated, but if something goes wrong we will make it right — contact us.</p>

      <H>3. AI-Generated Content</H>
      <p>Study content is generated by AI language models. It is a research aid, not a substitute for your own study, judgment, or the counsel of your community. Citations, dates, quotes, and archaeological details should be verified before use in academic or published work. We do not guarantee the accuracy, completeness, or theological alignment of generated content.</p>

      <H>4. Acceptable Use</H>
      <p>You agree not to abuse the service: no automated scraping or bulk generation, no attempts to bypass payment or rate limits, no reselling of generated content as a competing service, and no use that violates applicable law.</p>

      <H>5. Intellectual Property</H>
      <p>You may use generated study content freely in your sermons, lessons, papers, and ministry work. The PassageLab name, design, and software remain our property. Bible text is drawn from public domain translations (KJV, WEB, ASV, YLT).</p>

      <H>6. Affiliate Links</H>
      <p>Book recommendations are currently provided for reference only and do not contain affiliate or purchase links. If we introduce affiliate links (such as Amazon, Logos, or Christianbook) in the future, we may earn a commission on purchases at no extra cost to you, and this section will be updated to reflect that.</p>

      <H>7. AI-Generated Content &amp; Citations</H>
      <p>All study content — analysis, commentary, and the Sources page — is generated by artificial intelligence (Claude, by Anthropic) trained on a broad corpus of biblical scholarship, theology, and primary texts. It is a research aid, not a substitute for primary sources or your own scholarly judgment. Suggested sources and citations are AI-generated and may contain errors or omissions; you are responsible for verifying every source — author, edition, year, and page numbers — against an authoritative library catalog or database before relying on or citing it. We make no warranty as to the accuracy or completeness of generated content or citations.</p>

      <H>8. Disclaimers &amp; Liability</H>
      <p>The service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law, our total liability for any claim arising from the service is limited to the amount you paid us in the three months before the claim.</p>

      <H>9. Changes &amp; Termination</H>
      <p>We may update these terms or modify the service; material changes will be announced on this page. You may close your account at any time; outstanding usage will be billed in the next cycle. We may suspend accounts that violate these terms.</p>

      <H>10. Contact</H>
      <p>Questions about these terms: <a href="mailto:support@passagelab.app" style={{ color: '#C9973A' }}>support@passagelab.app</a></p>
    </div>
  )
}
