export type Role = 'pastor' | 'theologian' | 'teacher' | 'smallgroup' | 'youth' | 'children'

export const ROLE_TABS: Record<Role, string[]> = {
  pastor:     ['overview','scripture','language','history','archaeology','christ','commentary','illustrations','outline','manuscript'],
  theologian: ['overview','scripture','language','history','archaeology','theology','crossref','christ','commentary','fathers','books','news'],
  teacher:    ['overview','scripture','history','christ','commentary','illustrations','outline','smallgroup','books'],
  smallgroup: ['overview','scripture','history','christ','illustrations','smallgroup'],
  youth:      ['overview','scripture','history','christ','illustrations','youth'],
  children:   ['overview','scripture','illustrations','children'],
}

const TAB_ORDER = ['overview','scripture','language','history','archaeology','theology','crossref','christ','commentary','fathers','quotes','books','illustrations','news','outline','manuscript','smallgroup','youth','children']

export function getTabsForRoles(roles: Role[]): string[] {
  const tabSet = new Set<string>()
  roles.forEach(role => ROLE_TABS[role]?.forEach(tab => tabSet.add(tab)))
  return TAB_ORDER.filter(t => tabSet.has(t))
}

const TAB_PROMPTS: Record<string, (passage: string) => string> = {

  overview: (p) => `You are a world-class biblical scholar. Analyze "${p}" and return ONLY raw JSON starting with { ending with }.
{"overview":{"summary":"Write a rich 4-5 sentence summary capturing the full narrative arc, theological significance, and why this passage matters for the church today","main_idea":"One crisp unforgettable sentence — the single preachable proposition of this entire passage","author":"Author name, their background, writing context, relationship to the audience, and why all of that shapes how we read this passage","audience":"Detailed description of the original audience — who they were, their struggles, their cultural moment, what they already believed, what challenged them","date":"Approximate date written with explanation of why the historical moment matters for interpretation","setting":"Rich 3-4 sentence description of the historical, geographical, and cultural setting that shaped this passage","purpose":"The author's specific intent — what problem or question prompted this writing, what response they hoped to evoke","literary_genre":"Genre identification and full explanation of how this genre shapes interpretation, what rules apply, what mistakes readers make","literary_structure":"Detailed analysis of the passage's structure — chiasm, inclusio, parallel structure, narrative arc, rhetorical argument — and what the structure reveals about meaning","themes":["Major theme 1","Major theme 2","Major theme 3","Major theme 4","Major theme 5","Major theme 6"],"teaching_opportunities":["Specific teaching angle 1 with explanation","Specific teaching angle 2","Specific teaching angle 3","Specific teaching angle 4"]}}`,

  scripture: (p) => `You are a world-class biblical scholar and exegete. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"scripture":{"key_verse":"The single most preachable verse from this passage with a full explanation of why it is the theological hinge — what is lost if you miss it","verse_by_verse":[{"verse":"First verse reference","notes":"Rich 4-5 sentence exegetical note — what the original language reveals, what translators wrestle with, what the verse contributes to the argument, what preachers consistently miss, and one insight that will surprise even experienced readers"},{"verse":"Second verse reference","notes":"4-5 sentence exegetical note"},{"verse":"Third verse reference","notes":"4-5 sentence exegetical note"},{"verse":"Fourth verse reference","notes":"4-5 sentence note"},{"verse":"Fifth verse reference","notes":"4-5 sentence note"}]}}`,

  language: (p) => `You are a professor of biblical languages at a world-class seminary. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"language":[{"word":"Most theologically significant Greek or Hebrew word in this passage","transliteration":"Full transliteration","strongs":"G#### or H####","pos":"Part of speech","parsing":"Full morphological parsing if verb — tense, voice, mood, person, number","definition":"Rich 4-5 sentence definition covering full semantic range, etymology, historical development of meaning, and what the word meant to original readers","usage":"How this specific word is used across the entire canon — give 4-5 specific cross-references with brief explanation of each usage that illuminates the meaning here","cognates":"Related words in the same word family — what they reveal about the root meaning","preaching_note":"3-4 sentences on what this word specifically unlocks for the preacher — what illustration it suggests, what modern equivalent captures it, what is lost in translation"},{"word":"Second most significant word","transliteration":"t","strongs":"G####","pos":"pos","parsing":"parsing","definition":"4-5 sentence definition","usage":"Canonical usage with examples","cognates":"cognates","preaching_note":"3-4 sentences"},{"word":"Third significant word","transliteration":"t","strongs":"G####","pos":"pos","parsing":"parsing","definition":"4-5 sentence definition","usage":"Canonical usage","cognates":"cognates","preaching_note":"3-4 sentences"},{"word":"Fourth word","transliteration":"t","strongs":"H####","pos":"pos","parsing":"","definition":"definition","usage":"usage","cognates":"cognates","preaching_note":"note"},{"word":"Fifth word","transliteration":"t","strongs":"G####","pos":"pos","parsing":"","definition":"definition","usage":"usage","cognates":"cognates","preaching_note":"note"}]}`,

  history: (p) => `You are a world-class biblical historian and archaeologist. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"history":{"political":"3-4 sentences on the political environment — rulers, empires, power dynamics, political tensions that directly affect interpretation of this passage","religious":"3-4 sentences on the religious climate — competing sects, practices, controversies, expectations that illuminate the passage","economic":"2-3 sentences on economic conditions — wealth, poverty, trade, taxation directly relevant to understanding this text","social":"3-4 sentences on social customs, honor-shame dynamics, family structures, gender roles, patron-client relationships that directly affect the text","geographical":"2-3 sentences on geographical details that matter for interpretation — distances, terrain, climate, significance of specific locations mentioned","original_audience":"4-5 sentences on what the original audience immediately grasped that modern readers miss — specific cultural knowledge they brought to the text that completely changes its meaning","blind_spots":"4-5 sentences on what modern Western readers specifically miss or misread — cultural assumptions we import that distort the text","jewish_background":"3-4 sentences on Jewish background essential for unlocking this text — specific OT allusions, rabbinic traditions, Second Temple Judaism","greco_roman":"3-4 sentences on Greco-Roman context affecting interpretation — philosophy, rhetoric, social institutions, religious practices","marriage_family":"2-3 sentences on marriage, family, or household customs relevant to this passage","intertestamental":"2-3 sentences on the intertestamental period developments that form the immediate background of this passage"}}`,

  archaeology: (p) => `You are a leading biblical archaeologist. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"archaeology":[{"discovery":"Name of a real, specific archaeological discovery, excavation site, or artifact directly relevant to this passage","location":"Specific site, city, and region","date_found":"When discovered, by whom, and under what institution","relevance":"3-4 sentences on how this specific discovery directly illuminates, confirms, challenges, or contextualizes this passage — be specific","details":"4-5 sentences of rich archaeological detail — exactly what was found, what condition it was in, what the inscriptions or artifacts revealed, what scholarly debate surrounds it","significance":"3-4 sentences on why this matters for preachers and teachers — what it does to the text when you know this, what illustration it provides, how it makes the ancient world concrete"},{"discovery":"Second real discovery","location":"location","date_found":"date","relevance":"3-4 sentences","details":"4-5 sentences","significance":"3-4 sentences"},{"discovery":"Third real discovery","location":"location","date_found":"date","relevance":"relevance","details":"details","significance":"significance"},{"discovery":"Fourth discovery","location":"location","date_found":"date","relevance":"relevance","details":"details","significance":"significance"}]}`,

  theology: (p) => `You are a systematic theologian and biblical theology scholar. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"theology":{"god":"4-5 sentences on what this passage specifically reveals about the nature, character, and acts of God — which divine attributes are on display and how","christ":"4-5 sentences on Christological content — explicit or implicit, how Christ relates to this text, what it reveals about his person and work","holy_spirit":"3-4 sentences on pneumatological content — the Spirit's role and work in or behind this passage","salvation":"4-5 sentences on soteriological themes — sin, grace, faith, redemption, justification, sanctification as they appear here","humanity":"3-4 sentences on anthropological content — what this reveals about human nature, dignity, sin, responsibility, need","kingdom":"3-4 sentences on kingdom of God themes — present and future dimensions, already-not-yet tension","covenant":"3-4 sentences on covenant themes — which covenant is operative, what it demands and promises, how it connects to the larger covenant story","church":"3-4 sentences on ecclesiological themes — community, body life, mission, worship as they appear here","eschatology":"3-4 sentences on eschatological themes — judgment, hope, new creation, return of Christ as they surface here","biblical_theology":"5-6 sentences on how this passage fits the grand sweep — creation, fall, redemption, new creation — and where it sits in progressive revelation","systematic_connections":"4-5 sentences connecting to systematic theology — which loci this passage contributes to and how","practical_theology":"3-4 sentences on practical theology implications — how this shapes Christian living, ethics, community, worship","doctrinal_issues":["Full sentence describing a doctrinal debate or issue this passage addresses and the positions taken","Second doctrinal issue with the interpretive options","Third issue","Fourth issue"]}}`,

  crossref: (p) => `You are a biblical scholar specializing in intertextuality. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"crossrefs":{"direct":["Reference 1 — 2-3 sentence explanation of the direct verbal or conceptual connection","Reference 2 — explanation","Reference 3 — explanation","Reference 4 — explanation","Reference 5 — explanation","Reference 6 — explanation"],"prophetic":["Reference 1 — how this fulfills or anticipates prophecy","Reference 2 — explanation","Reference 3 — explanation"],"typological":["Reference 1 — the type and how it points to this passage or Christ","Reference 2 — explanation","Reference 3 — explanation"],"thematic":["Reference 1 — the shared theme and how the passages illuminate each other","Reference 2 — explanation","Reference 3 — explanation","Reference 4 — explanation"],"parallel_passages":["Reference 1 — how this parallel illuminates the meaning","Reference 2 — explanation"],"ot_backdrop":"Rich 4-5 sentence description of the Old Testament backdrop — the specific texts, themes, and promises that form the foundation of this passage","nt_development":"3-4 sentences on how the NT develops or fulfills what this passage anticipates, or how this NT passage builds on OT foundations"}}`,

  christ: (p) => `You are a biblical theologian specializing in Christology and redemptive-historical interpretation. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"christ":{"title":"The most fitting Christological title surfaced by this passage with 2-3 sentences explaining why this title is appropriate and what it reveals","presence":"4-5 sentences on how Christ is present in this text — explicit statements, implicit presence, typological foreshadowing, thematic anticipation","foreshadowing":"4-5 sentences on specific images, types, themes, and patterns in this passage that point forward to Christ — be specific about the connection","fulfillment":"4-5 sentences on how Christ specifically fulfills what this text anticipates or establishes — what he does that no one else could","gospel_thread":"5-6 sentences on the gospel thread running through this passage — creation, fall, redemption, restoration — and how the good news of Jesus emerges from this specific text","redemptive_historical":"4-5 sentences on where this passage sits in redemptive history — before or after the cross, what that location means, how it shapes interpretation and application","christocentric_preaching":"5-6 sentences on the legitimate exegetical path from this text to Christ — how to preach Christ without allegorizing, moralizing, or forcing the connection — what makes this both faithful and compelling"}}`,

  commentary: (p) => `You are a theological librarian and commentary scholar with mastery of the entire commentary tradition. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"commentary":{"matthew_henry":"4-5 sentences summarizing Matthew Henry's key observations, his characteristic emphases, what he saw in this passage that others missed, and how his Puritan perspective shapes his reading","spurgeon":"4-5 sentences on Spurgeon's approach — what he emphasized, what illustrations he used, what made his preaching of this passage distinctive, and one insight from his sermons on this text","calvin":"4-5 sentences on Calvin's theological emphasis and exegetical moves — his Reformed hermeneutic applied here, where he pushes back against other interpreters, his pastoral concern","augustine":"4-5 sentences on Augustine's interpretation — his allegorical tendencies, his theological concerns, how his reading has shaped the tradition, what he uniquely contributes","luther":"4-5 sentences on Luther's emphasis — his Law-Gospel hermeneutic applied here, his pastoral intensity, his polemical context, what he saw that the medieval church missed","modern_reformed":"4-5 sentences on what modern Reformed scholarship (Carson, Piper, Sproul, Keller) emphasizes in this passage — their exegetical contributions and theological emphases","modern_evangelical":"4-5 sentences on broader modern evangelical scholarship — key interpretive debates, where consensus has formed, where scholars still disagree, recent contributions","areas_of_agreement":"4-5 sentences on where virtually all commentators across traditions agree — the exegetical bedrock that transcends theological differences","areas_of_debate":"4-5 sentences on where commentators significantly disagree — the real interpretive forks, why they matter, what is at stake in each position","best_insight":"3-4 sentences identifying the single most illuminating insight from the entire commentary tradition on this passage — the observation that most changes how you see the text"}}`,

  fathers: (p) => `You are a patristics scholar with expertise in early church interpretation. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"church_fathers":[{"father":"Church father name","dates":"Birth-death years","quote":"A substantial, representative quote or very close paraphrase of their actual words on this passage — something that captures their distinctive voice and theological emphasis","context":"3-4 sentences explaining the context of their interpretation — what theological controversy they were addressing, what their homiletical situation was, why their reading matters for us today"},{"father":"Second father","dates":"dates","quote":"substantial quote or paraphrase","context":"3-4 sentences"},{"father":"Third father","dates":"dates","quote":"substantial quote or paraphrase","context":"3-4 sentences"},{"father":"Fourth father","dates":"dates","quote":"substantial quote or paraphrase","context":"3-4 sentences"}]}`,

  books: (p) => `You are a theological librarian curating resources for serious Bible teachers. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"books":[{"title":"Exact book title","author":"Author full name","type":"Commentary or Theology or Background or Devotional or Language","description":"3-4 sentences on what this book specifically contributes to understanding this passage — what makes it valuable, what perspective it brings, what the reader will find that they cannot find elsewhere, what level of reader it suits","level":"Beginner or Intermediate or Advanced or Scholar"},{"title":"title","author":"author","type":"type","description":"3-4 sentences","level":"level"},{"title":"title","author":"author","type":"type","description":"3-4 sentences","level":"level"},{"title":"title","author":"author","type":"type","description":"3-4 sentences","level":"level"},{"title":"title","author":"author","type":"type","description":"3-4 sentences","level":"level"},{"title":"title","author":"author","type":"type","description":"3-4 sentences","level":"level"},{"title":"title","author":"author","type":"type","description":"3-4 sentences","level":"level"},{"title":"title","author":"author","type":"type","description":"3-4 sentences","level":"level"}]}`,

  illustrations: (p) => `You are a master preacher and illustration expert. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"illustrations":[{"category":"History","title":"Specific evocative title","content":"Rich vivid 5-6 sentence illustration from history. Name specific people, exact dates, real places. Make it emotionally resonant and theologically precise. The congregation should be able to see it.","bridge":"3-4 sentences on exactly how to connect this illustration to the passage — the explicit verbal bridge a preacher would use"},{"category":"Science or Nature","title":"Title","content":"A surprising scientific or natural phenomenon that illuminates a truth in this passage. Counterintuitive, specific, memorable. 5-6 sentences.","bridge":"3-4 sentence bridge to passage"},{"category":"Human Experience","title":"Title","content":"A universal human experience that opens a window into this text. Something every person in the room will immediately recognize from their own life. 5-6 sentences.","bridge":"3-4 sentence bridge"},{"category":"Current Culture","title":"Title","content":"A contemporary cultural moment, film, book, news story, or social trend that creates a bridge to this passage. Specific and current. 5-6 sentences.","bridge":"3-4 sentence bridge"},{"category":"Church History","title":"Title","content":"A story from church history — martyr, reformer, missionary, theologian — that embodies the truth of this passage. Specific, dramatic, theologically pointed. 5-6 sentences.","bridge":"3-4 sentence bridge"},{"category":"Pastoral","title":"Title","content":"A pastoral scenario that brings this passage to life — the kind of real-life moment where this text becomes urgent. Protect privacy — no real names or identifying details. 5-6 sentences.","bridge":"3-4 sentence bridge"},{"category":"Opening Hook","title":"Sermon Opening","content":"A powerful sermon opener — a question, scenario, cultural moment, or statement — that creates immediate tension and engagement and sets up this specific passage. 5-6 sentences.","bridge":"3-4 sentences on how to transition from this opening directly into the text"}]}`,

  news: (p) => `You are a biblical studies news editor tracking recent scholarship and discovery. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"news":[{"type":"Archaeological","headline":"Specific recent or representative archaeological finding related to this passage or its setting","source":"Journal, institution, or publication type","date":"Approximate date of finding","relevance":"3-4 sentences on how this finding directly illuminates the passage","summary":"4-5 sentence summary of the finding, what was discovered, what scholars concluded, and why it matters for biblical study"},{"type":"Scholarly","headline":"Recent academic development, commentary publication, or interpretive debate","source":"Academic journal or institution type","date":"Approximate date","relevance":"3-4 sentences on why this matters for teachers and preachers","summary":"4-5 sentence summary"},{"type":"Cultural","headline":"Contemporary news story or social trend making this passage urgently relevant today","source":"News or media type","date":"Recent","relevance":"3-4 sentences on why this makes the passage timely","summary":"4-5 sentences on why this matters for preaching right now"},{"type":"Scientific","headline":"Scientific discovery illuminating a truth in this passage","source":"Scientific publication type","date":"Recent","relevance":"Relevance to passage","summary":"Summary of significance"}]}`,

  outline: (p) => `You are a master homiletician and preaching coach. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"outline":{"title":"A compelling, memorable sermon title — alliterative, metaphorical, or question-based — that captures the big idea and makes someone want to hear this sermon","big_idea":"The big idea stated as a full preachable proposition — a complete sentence that captures the entire sermon in one memorable statement","introduction":"5-6 sentences describing how to open the sermon — a specific hook, question, scenario, or cultural moment that creates immediate tension and genuine need for what this passage says","points":[{"point":"First main point — stated memorably, could be alliterative — captures the first movement of the text","subpoints":["Detailed subpoint 1 with specific exegetical grounding from the text","Detailed subpoint 2 with theological development","Detailed subpoint 3 with contemporary connection"],"illustration":"3-4 sentence description of a specific illustration suited to this point — enough detail that a preacher knows exactly what to say","application":"3-4 sentences of specific, concrete, personal application — not generic but pointed at real life decisions and behaviors"},{"point":"Second main point","subpoints":["subpoint1","subpoint2","subpoint3"],"illustration":"3-4 sentence illustration","application":"3-4 sentences specific application"},{"point":"Third main point","subpoints":["subpoint1","subpoint2","subpoint3"],"illustration":"3-4 sentence illustration","application":"3-4 sentences specific application"}],"conclusion":"5-6 sentences on how to land the sermon — the closing movement, the final image or story, how to bring everything together around the big idea","invitation":"4-5 sentences on how to invite response — what does faithfulness to this text look like in concrete action this week, how to call for decision without manipulation","alternative_structures":["Narrative structure: describe exactly how to preach this passage as a story — the narrative arc, the tension, the resolution","Problem-solution: describe the human problem this passage addresses and how it resolves in the gospel","Question-driven: list the 3 questions this passage answers and how to structure the sermon around discovering each answer","Inductive approach: how to let the congregation discover the big idea rather than stating it upfront — the journey of the text"]}}`,

  manuscript: (p) => `You are a gifted preacher writing a full sermon manuscript. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"manuscript":{"intro":"Write a full 250-300 word introduction in real conversational preaching voice. A powerful hook that creates immediate tension and engagement. The transition that sets up why this passage matters right now. Written to be spoken, not read — contractions, short sentences, rhetorical questions. The congregation should lean forward.","body":"Write a full 900-1100 word sermon body covering all three main points with natural transitions between them. Illustrations embedded naturally — not announced but woven in. Application that is specific and personal, not generic. Theological depth that does not feel like a lecture. Gospel clarity in every point. Real preaching voice throughout — the kind of manuscript a gifted communicator would actually deliver on Sunday morning.","conclusion":"Write a full 250-300 word conclusion. Land the big idea with clarity and emotional force. Gospel application — what Christ has done in light of this text. A specific call to action that is concrete and achievable. A final image or sentence that will stay with the congregation all week. End strong."}}`,

  smallgroup: (p) => `You are a small group ministry expert and curriculum developer. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"smallgroup":{"icebreaker":"A fun, low-stakes opening question that connects naturally to the passage theme without requiring any Bible knowledge — something that gets people talking and laughing","context_setter":"2-3 sentences a small group leader can read aloud to set up the passage for people who may not have heard the sermon — enough background to ground the discussion","questions":[{"type":"Observation","question":"A specific factual question that forces people into the text — what does it actually say, not what do they think it means"},{"type":"Observation","question":"A second observation question that draws attention to something easy to overlook — a detail, a word, a structural feature"},{"type":"Observation","question":"A third observation question about the flow or structure of the passage"},{"type":"Interpretation","question":"What does this mean — a deeper question about the text's significance, not just its content"},{"type":"Interpretation","question":"Why did the author say it this way — a question about literary or theological choices that reveal meaning"},{"type":"Interpretation","question":"What would the original audience have understood that we might miss — connects to historical context"},{"type":"Interpretation","question":"A question about a difficult or debated element of the passage — honest about complexity"},{"type":"Application","question":"Where do you see this truth most needed in your own life right now — specific and personal, not general"},{"type":"Application","question":"What would it actually look like to live this out this week — concrete, measurable, achievable"},{"type":"Application","question":"Who in your life needs to hear the truth of this passage — outward facing, missional"},{"type":"Prayer","question":"Based on what we discussed, what is one specific thing you want to ask God for this week"}],"activity":"A creative group activity or exercise that moves beyond discussion into experience — something that makes the passage concrete and memorable","deeper_study":["A specific commentary, article, or cross-reference for those who want to go deeper — with explanation of why","A second deeper study resource or question","A third option for the most motivated group members"],"takeaway":"The one sentence you want every group member to carry with them all week — memorable, personal, actionable"}}`,

  youth: (p) => `You are a gifted youth pastor and curriculum developer. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"youth":{"big_truth":"The main truth of this passage in language a 16-year-old would find genuinely compelling — not dumbed down but translated into their world and concerns","cultural_hook":"A specific cultural reference, trend, social media phenomenon, or issue teens are actually facing that creates a natural bridge to this passage — current and specific","game":"A specific, playable game or activity with full instructions that sets up the passage theme — something that actually works with teenagers and creates the right emotional and intellectual setup","object_lesson":{"object":"A specific common object that every teenager has encountered","lesson":"Step-by-step instructions on how to use this object to teach the main truth — what you do, what you say, what the reveal is"},"discussion_questions":["A question teenagers will actually engage with — relevant to their real world","A second question that goes a level deeper","A third question that challenges comfortable assumptions","A fourth question for mature students — harder, more honest, more personal"],"challenge":"A specific, concrete challenge or dare for the week — something a teenager can actually do that embodies the passage's truth and is different enough to be memorable","memory_verse":"The best verse from this passage for teenagers to memorize — short enough to actually memorize, meaningful enough to matter — with a 2-3 sentence explanation of why this verse"}}`,

  children: (p) => `You are a gifted children's ministry director and curriculum developer. Passage: "${p}". Return ONLY raw JSON starting with { ending with }.
{"children":{"big_truth":"One truth from this passage in words a 7-year-old completely understands — simple but not shallow, concrete not abstract","memory_verse":"The best memory verse for children — short enough for a 6-year-old to memorize, with reference, chosen because it captures the main truth in the simplest possible words","story_retelling":"Write a vivid, present-tense retelling of this passage as a children's story — 150-200 words, engaging, sensory, age-appropriate language throughout, written to be read aloud by a teacher. Children should be able to see it happening.","object_lesson":{"object":"A simple household object every family has — something children can recognize immediately","lesson":"Detailed step-by-step instructions on how to use this object to teach the passage's main truth — what you show, what you say, what questions you ask, what the lesson is"},"craft_idea":"A specific craft idea with complete materials list and step-by-step instructions that reinforces the lesson — something achievable in 10-15 minutes with basic supplies","activity":"An active game or physical activity with specific instructions that teaches the passage — children learn by moving, make it energetic and connected to the truth","snack_idea":"A specific snack that connects thematically to the passage with a clear explanation of the connection — something simple, allergy-aware, and fun","discussion_questions":["A simple, engaging question for ages 6-10 that a child can actually answer from the story","A second question that goes a little deeper","A third question that connects the story to their daily life"],"parent_connection":"A specific, actionable take-home for parents — a dinner table question, a bedtime prayer they can pray together, or a week-long family challenge — rooted in this passage and simple enough that busy parents will actually do it"}}`,
}

export function buildTabPrompt(tabId: string, passage: string): string {
  const builder = TAB_PROMPTS[tabId]
  if (!builder) return ''
  return builder(passage)
}

// Keep for compatibility
export function buildPrompt(passage: string, tabs: string[], part: 1 | 2): string {
  return ''
}