export type Role = 'pastor' | 'theologian' | 'teacher' | 'smallgroup' | 'youth' | 'children'

export const ROLE_TABS: Record<Role, string[]> = {
  pastor:     ['overview','scripture','language','history','archaeology','christ','commentary','illustrations','outline','manuscript'],
  theologian: ['overview','scripture','language','history','archaeology','theology','crossref','christ','commentary','fathers','books','news'],
  teacher:    ['overview','scripture','history','christ','commentary','illustrations','outline','smallgroup','books'],
  smallgroup: ['overview','scripture','history','christ','illustrations','smallgroup'],
  youth:      ['overview','scripture','history','christ','illustrations','youth'],
  children:   ['overview','scripture','illustrations','children'],
}

const TAB_ORDER = ['overview','scripture','language','history','archaeology','theology','crossref','christ','commentary','fathers','quotes','books','illustrations','news','outline','manuscript','smallgroup','youth','children']

export function getTabsForRoles(roles: Role[]): string[] {
  const tabSet = new Set<string>()
  roles.forEach(role => ROLE_TABS[role]?.forEach(tab => tabSet.add(tab)))
  return TAB_ORDER.filter(t => tabSet.has(t))
}

const TAB_PROMPTS: Record<string, (passage: string) => string> = {

  overview: (p) => `You are a world-class biblical scholar. Analyze "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"overview":{"summary":"Rich 4-5 sentence summary capturing full narrative arc and theological significance","main_idea":"One crisp preachable proposition — the single sentence that captures the whole passage","author":"Author name, background, writing context, and why that shapes interpretation","audience":"Detailed original audience — who they were, their struggles, cultural moment, what challenged them","date":"Approximate date with explanation of why the historical moment matters","setting":"Rich 3-4 sentence historical, geographical, cultural setting","purpose":"Author's specific intent — what problem prompted this, what response was hoped for","literary_genre":"Genre and full explanation of how it shapes interpretation and what mistakes readers make","literary_structure":"Detailed structure analysis — chiasm, inclusio, narrative arc, rhetorical argument — and what structure reveals about meaning","themes":["Theme 1","Theme 2","Theme 3","Theme 4","Theme 5","Theme 6"],"teaching_opportunities":["Specific angle 1 with full explanation","Specific angle 2 with explanation","Specific angle 3 with explanation","Specific angle 4 with explanation"]}}`,

  scripture: (p) => `You are a world-class biblical exegete. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"scripture":{"key_verse":"Most preachable verse with full explanation of why it is the theological hinge","verse_by_verse":[{"verse":"First verse reference","notes":"Rich 4-5 sentence exegetical note — original language, translation debates, what the verse contributes to the argument, what preachers miss, one insight that surprises even experienced readers"},{"verse":"Second verse reference","notes":"4-5 sentence note"},{"verse":"Third verse reference","notes":"4-5 sentence note"},{"verse":"Fourth verse reference","notes":"4-5 sentence note"},{"verse":"Fifth verse reference","notes":"4-5 sentence note"}]}}`,

  language: (p) => `You are a seminary professor of biblical languages. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"language":[{"word":"Most significant Greek or Hebrew word","transliteration":"full transliteration","strongs":"G#### or H####","pos":"part of speech","parsing":"full morphological parsing if verb","definition":"Rich 4-5 sentence definition — semantic range, etymology, historical development, what it meant to original readers","usage":"4-5 specific cross-references showing how this word is used across the canon with brief explanation of each","cognates":"Related words in same word family and what they reveal","preaching_note":"3-4 sentences on what this word unlocks for the preacher — what illustration it suggests, what is lost in translation"},{"word":"Second significant word","transliteration":"t","strongs":"G####","pos":"pos","parsing":"parsing","definition":"4-5 sentence definition","usage":"canonical usage with examples","cognates":"cognates","preaching_note":"3-4 sentences"},{"word":"Third significant word","transliteration":"t","strongs":"G####","pos":"pos","parsing":"parsing","definition":"4-5 sentence definition","usage":"canonical usage","cognates":"cognates","preaching_note":"3-4 sentences"},{"word":"Fourth word","transliteration":"t","strongs":"H####","pos":"pos","parsing":"","definition":"definition","usage":"usage","cognates":"cognates","preaching_note":"note"},{"word":"Fifth word","transliteration":"t","strongs":"G####","pos":"pos","parsing":"","definition":"definition","usage":"usage","cognates":"cognates","preaching_note":"note"}]}`,

  history: (p) => `You are a world-class biblical historian. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"history":{"political":"3-4 sentences on political environment affecting interpretation","religious":"3-4 sentences on religious climate illuminating the passage","economic":"2-3 sentences on economic conditions relevant to the text","social":"3-4 sentences on social customs, honor-shame dynamics, family structures","geographical":"2-3 sentences on geographical details that matter for interpretation","original_audience":"4-5 sentences on what original audience grasped that moderns miss","blind_spots":"4-5 sentences on what modern Western readers specifically miss","jewish_background":"3-4 sentences on Jewish background essential for unlocking this text","greco_roman":"3-4 sentences on Greco-Roman context affecting interpretation","marriage_family":"2-3 sentences on marriage or family customs if relevant","intertestamental":"2-3 sentences on intertestamental period background"}}`,

  archaeology: (p) => `You are a leading biblical archaeologist. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"archaeology":[{"discovery":"Name of real specific archaeological discovery directly relevant to this passage","location":"Specific site and region","date_found":"When discovered and by whom","relevance":"3-4 sentences on how this illuminates the passage","details":"4-5 sentences of rich archaeological detail — what was found, scholarly conclusions, ongoing debate","significance":"3-4 sentences on why this matters for preachers — what it does to the text"},{"discovery":"Second real discovery","location":"loc","date_found":"date","relevance":"3-4 sentences","details":"4-5 sentences","significance":"3-4 sentences"},{"discovery":"Third discovery","location":"loc","date_found":"date","relevance":"relevance","details":"details","significance":"significance"},{"discovery":"Fourth discovery","location":"loc","date_found":"date","relevance":"relevance","details":"details","significance":"significance"}]}`,

  theology: (p) => `You are a systematic and biblical theologian. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"theology":{"god":"4-5 sentences on what this passage reveals about God's nature and character","christ":"4-5 sentences on Christological content — explicit or implicit","holy_spirit":"3-4 sentences on the Spirit's role in this passage","salvation":"4-5 sentences on soteriological themes","humanity":"3-4 sentences on anthropological content","kingdom":"3-4 sentences on kingdom of God themes","covenant":"3-4 sentences on covenant themes","church":"3-4 sentences on ecclesiological themes","eschatology":"3-4 sentences on eschatological themes","biblical_theology":"5-6 sentences on how this fits creation-fall-redemption-new creation","systematic_connections":"4-5 sentences connecting to systematic theology","practical_theology":"3-4 sentences on practical theology implications","doctrinal_issues":["Full sentence describing doctrinal issue 1","Issue 2","Issue 3","Issue 4"]}}`,

  crossref: (p) => `You are a biblical scholar specializing in intertextuality. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"crossrefs":{"direct":["ref1 — 2-3 sentence explanation","ref2 — explanation","ref3 — explanation","ref4 — explanation","ref5 — explanation","ref6 — explanation"],"prophetic":["ref1 — explanation","ref2 — explanation","ref3 — explanation"],"typological":["ref1 — explanation","ref2 — explanation","ref3 — explanation"],"thematic":["ref1 — explanation","ref2 — explanation","ref3 — explanation","ref4 — explanation"],"parallel_passages":["ref1 — explanation","ref2 — explanation"],"ot_backdrop":"Rich 4-5 sentence OT backdrop","nt_development":"3-4 sentences on how NT develops this passage"}}`,

  christ: (p) => `You are a biblical theologian specializing in Christology. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"christ":{"title":"Most fitting Christological title with 2-3 sentences explaining why","presence":"4-5 sentences on how Christ is present — explicit, implicit, typological","foreshadowing":"4-5 sentences on specific images pointing forward to Christ","fulfillment":"4-5 sentences on how Christ fulfills what this text anticipates","gospel_thread":"5-6 sentences on the gospel thread — creation, fall, redemption, restoration","redemptive_historical":"4-5 sentences on where this sits in redemptive history","christocentric_preaching":"5-6 sentences on the legitimate exegetical path from text to Christ"}}`,

  commentary: (p) => `You are a theological librarian with mastery of the entire commentary tradition. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"commentary":{"matthew_henry":"4-5 sentences on Matthew Henry's key observations and Puritan emphases","spurgeon":"4-5 sentences on Spurgeon's approach, what he emphasized, his distinctive insight","calvin":"4-5 sentences on Calvin's theological emphasis and exegetical moves","augustine":"4-5 sentences on Augustine's interpretation and what he uniquely contributes","luther":"4-5 sentences on Luther's emphasis and what he saw that the medieval church missed","modern_reformed":"4-5 sentences on modern Reformed scholarship — Carson, Piper, Sproul, Keller","modern_evangelical":"4-5 sentences on broader modern evangelical scholarship and key debates","areas_of_agreement":"4-5 sentences on where all commentators across traditions agree","areas_of_debate":"4-5 sentences on where commentators significantly disagree and what is at stake","best_insight":"3-4 sentences identifying the single most illuminating insight from the entire commentary tradition"}}`,

  fathers: (p) => `You are a patristics scholar. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"church_fathers":[{"father":"Father name","dates":"birth-death years","quote":"Substantial representative quote or very close paraphrase capturing their distinctive voice","context":"3-4 sentences on the context of their interpretation and why it matters today"},{"father":"Second father","dates":"dates","quote":"substantial quote","context":"3-4 sentences"},{"father":"Third father","dates":"dates","quote":"substantial quote","context":"3-4 sentences"},{"father":"Fourth father","dates":"dates","quote":"substantial quote","context":"3-4 sentences"}]}`,

  books: (p) => `You are a theological librarian curating resources for serious Bible teachers. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"books":[{"title":"Exact book title","author":"Full author name","type":"Commentary or Theology or Background or Devotional or Language","description":"3-4 sentences on what this book specifically contributes — what makes it valuable, what the reader finds that they cannot find elsewhere","level":"Beginner or Intermediate or Advanced or Scholar"},{"title":"t","author":"a","type":"type","description":"3-4 sentences","level":"Intermediate"},{"title":"t","author":"a","type":"type","description":"3-4 sentences","level":"Advanced"},{"title":"t","author":"a","type":"type","description":"3-4 sentences","level":"Scholar"},{"title":"t","author":"a","type":"type","description":"3-4 sentences","level":"Beginner"},{"title":"t","author":"a","type":"type","description":"3-4 sentences","level":"Intermediate"},{"title":"t","author":"a","type":"type","description":"3-4 sentences","level":"Advanced"},{"title":"t","author":"a","type":"type","description":"3-4 sentences","level":"Scholar"}]}`,

  illustrations: (p) => `You are a master preacher and illustration expert. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"illustrations":[{"category":"History","title":"Specific evocative title","content":"Rich vivid 5-6 sentence historical illustration. Specific people, dates, places. Emotionally resonant and theologically precise.","bridge":"3-4 sentences on exactly how to connect this to the passage"},{"category":"Science or Nature","title":"Title","content":"Surprising scientific or natural phenomenon illuminating a truth here. 5-6 sentences.","bridge":"3-4 sentence bridge"},{"category":"Human Experience","title":"Title","content":"Universal human experience opening a window into this text. 5-6 sentences.","bridge":"3-4 sentence bridge"},{"category":"Current Culture","title":"Title","content":"Contemporary cultural moment creating a bridge to this passage. 5-6 sentences.","bridge":"3-4 sentence bridge"},{"category":"Church History","title":"Title","content":"Story from church history embodying this passage. Specific and dramatic. 5-6 sentences.","bridge":"3-4 sentence bridge"},{"category":"Pastoral","title":"Title","content":"Pastoral scenario where this text becomes urgent. Protect privacy. 5-6 sentences.","bridge":"3-4 sentence bridge"},{"category":"Opening Hook","title":"Sermon Opening","content":"Powerful sermon opener creating immediate tension and engagement. 5-6 sentences.","bridge":"3-4 sentences transitioning into the text"}]}`,

  news: (p) => `You are a biblical studies editor tracking recent scholarship and discovery. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"news":[{"type":"Archaeological","headline":"Specific recent archaeological finding related to this passage","source":"Journal or institution type","date":"Approximate date","relevance":"3-4 sentences on how this illuminates the passage","summary":"4-5 sentence summary of the finding and significance"},{"type":"Scholarly","headline":"Recent academic development or interpretive debate","source":"Academic source type","date":"Approximate date","relevance":"3-4 sentences on why this matters for teachers","summary":"4-5 sentence summary"},{"type":"Cultural","headline":"Contemporary development making this passage urgently relevant today","source":"News or media type","date":"Recent","relevance":"3-4 sentences on why this is timely","summary":"4-5 sentences on why this matters for preaching now"},{"type":"Scientific","headline":"Scientific discovery illuminating a truth in this passage","source":"Scientific publication type","date":"Recent","relevance":"Relevance to passage","summary":"4-5 sentence summary"}]}`,

  outline: (p) => `You are a master homiletician and preaching coach. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"outline":{"title":"Compelling memorable sermon title — alliterative or metaphorical — that makes someone want to hear this sermon","big_idea":"Full preachable proposition — one complete sentence capturing the entire sermon","introduction":"5-6 sentences on how to open — specific hook creating genuine tension and need for what this passage says","points":[{"point":"First main point — stated memorably","subpoints":["Detailed subpoint 1 with exegetical grounding","Detailed subpoint 2 with theological development","Detailed subpoint 3 with contemporary connection"],"illustration":"3-4 sentences describing a specific illustration","application":"3-4 sentences of specific concrete personal application"},{"point":"Second main point","subpoints":["subpoint1","subpoint2","subpoint3"],"illustration":"3-4 sentence illustration","application":"3-4 sentences application"},{"point":"Third main point","subpoints":["subpoint1","subpoint2","subpoint3"],"illustration":"3-4 sentence illustration","application":"3-4 sentences application"}],"conclusion":"5-6 sentences on how to land the sermon — closing movement, final image, bringing everything together","invitation":"4-5 sentences on how to invite response — concrete action this week","alternative_structures":["Narrative structure: full description of how to preach this as a story","Problem-solution: the human problem this passage addresses and how it resolves in the gospel","Question-driven: 3 questions this passage answers and how to structure around them","Inductive: how to let the congregation discover the big idea rather than stating it upfront"]}}`,

  manuscript: (p) => `You are a gifted preacher writing a full sermon manuscript. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"manuscript":{"intro":"Write a full 250-300 word introduction in real conversational preaching voice. Powerful hook creating immediate tension. The congregation should lean forward. Written to be spoken — contractions, short sentences, rhetorical questions.","body":"Write a full 900-1000 word sermon body covering all three main points with natural transitions. Illustrations embedded naturally. Application specific and personal. Theological depth that does not feel like a lecture. Gospel clarity in every point. Real preaching voice throughout.","conclusion":"Write a full 250-300 word conclusion. Land the big idea with clarity and force. Gospel application. Specific call to action. A final image that will stay with the congregation all week."}}`,

  smallgroup: (p) => `You are a small group ministry expert. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"smallgroup":{"icebreaker":"Fun low-stakes opening question connecting to passage theme without requiring Bible knowledge","context_setter":"2-3 sentences a leader can read aloud to set up the passage","questions":[{"type":"Observation","question":"Specific factual question forcing people into the text"},{"type":"Observation","question":"Second observation question about something easy to overlook"},{"type":"Observation","question":"Third observation about structure or flow"},{"type":"Interpretation","question":"What does this mean — deeper question about significance"},{"type":"Interpretation","question":"Why did the author say it this way"},{"type":"Interpretation","question":"What would original audience have understood"},{"type":"Interpretation","question":"Question about a difficult or debated element"},{"type":"Application","question":"Where is this truth most needed in your life right now"},{"type":"Application","question":"What would living this out look like this week — concrete"},{"type":"Application","question":"Who in your life needs to hear this — outward facing"},{"type":"Prayer","question":"Based on this passage what do you want to ask God for"}],"activity":"Creative group activity moving beyond discussion into experience","deeper_study":["Specific resource for deeper study 1","Suggestion 2","Suggestion 3"],"takeaway":"One sentence every group member should carry all week"}}`,

  youth: (p) => `You are a gifted youth pastor. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"youth":{"big_truth":"Main truth in language a 16-year-old finds genuinely compelling","cultural_hook":"Specific cultural reference or teen issue creating natural bridge to this passage","game":"Specific playable game with full instructions setting up the passage theme","object_lesson":{"object":"Specific common object every teenager knows","lesson":"Step-by-step instructions — what you do, what you say, what the reveal is"},"discussion_questions":["Question teens will actually engage with","Second question going deeper","Third challenging assumptions","Fourth for mature students — harder and more personal"],"challenge":"Specific concrete weekly challenge — something a teenager can actually do","memory_verse":"Best verse with 2-3 sentence explanation of why this verse for teens"}}`,

  children: (p) => `You are a gifted children's ministry director. Passage: "${p}".
Return ONLY raw JSON. No markdown. No backticks. Start with { end with }.
{"children":{"big_truth":"One truth in words a 7-year-old completely understands — simple but not shallow","memory_verse":"Best short memory verse with reference — short enough for a 6-year-old","story_retelling":"Vivid present-tense retelling as children's story — 150-200 words, sensory, age-appropriate, written to be read aloud","object_lesson":{"object":"Simple household object every family has","lesson":"Detailed step-by-step teaching instructions — what to show, say, ask, and conclude"},"craft_idea":"Specific craft with complete materials list and step-by-step instructions","activity":"Active game or physical activity with specific instructions","snack_idea":"Thematic snack with clear explanation of the connection","discussion_questions":["Simple engaging question for ages 6-10","Second question","Third connecting story to daily life"],"parent_connection":"Specific actionable take-home — dinner table question, bedtime prayer, or family challenge simple enough that busy parents will actually do it"}}`,
}

export function buildTabPrompt(tabId: string, passage: string): string {
  const builder = TAB_PROMPTS[tabId]
  if (!builder) return ''
  return builder(passage)
}

export function buildPrompt(passage: string, tabs: string[], part: 1 | 2): string {
  return ''
}